### ISSUE TITLE
Cannot set property 'DatadogServerless...' of undefined

### ISSUE THREAD

**Issue by ohnu** [DataDog/datadog-cloudformation-macro#22] opened 2020-11-11 15:38 UTC
## Actual Behavior
We are receiving the following error:

 ❌  ConvertorService-development failed: Error: Failed to create ChangeSet CDK-a4f92cc3-e91c-42e3-8706-50d1416ddc22 on ConvertorService-development: FAILED, Transform 588037597690::DatadogServerless failed with: Cannot set property 'DatadogServerlessMainHandler0B2856CD' of undefined
Failed to create ChangeSet CDK-a4f92cc3-e91c-42e3-8706-50d1416ddc22 on ConvertorService-development: FAILED, Transform 588037597690::DatadogServerless failed with: Cannot set property 'DatadogServerlessMainHandler0B2856CD' of undefined

## Steps to Reproduce the Problem
- appeared after update to latest version

## Specifications

  For the Datadog Serverless Macro:
  - Deployment method and version (CloudFormation, SAM, CDK): CDK (replicaates both with CDK  v1.69.0 & v1.73.0)
  - Datadog CloudFormation Macro version: 0.1.4
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 12
  
## Stacktrace
N/A - does not show up

## Observations
I've tried to trace this issue, and I think it might be related to https://github.com/DataDog/datadog-cloudformation-macro/pull/20/files 
Specifically at line 188 it is trying to set a value, but the `outputs` variable seem to be `undefined`.
To go around this I've manually edited  this line `const outputs = fragment.Outputs;` to have a fallback to an empty object and seemed to work. 
I do not have underlying knowledge to understand why the fragment's outputs are empty but they just seem to be that way in my case.

**Comment by johnchapin** [comment] 2020-11-12 22:19
I've been impacted by this as well.

My workaround in a SAM template is to add an `Outputs` key with an empty map as the value at the top level, like this:

```
Outputs: {}
```

**Comment by ohnu** [comment] 2020-12-14 08:53
@Hesperide @JacksonDavenport  any plans on fixing this ?

**Comment by tianchu** [comment] 2020-12-15 18:38
@ohnu This does sound like a regression in the latest version, we should be able to fix it. Meanwhile, for anyone encountering this issue, please try using version `0.1.3`.

**Comment by joeferraro** [comment] 2021-01-18 18:57
We are also encountering an issue related to outputs. The exception we receive references an unresolved element "in the Outputs block of the template." Removing the datadog macro allows the template to be deployed.

**Comment by tianchu** [comment] 2021-08-06 15:59
We have rolled out quite a few new versions since the issue being reported and lots of the implementation has changed. Is anyone still experiencing this issue on the latest version?

**Comment by hghotra** [comment] 2021-11-04 12:22
@ohnu closing this issue for now, please let us know if you're still running into this issue.

**Closed by hghotra** 2021-11-04 12:22 UTC
Labels: bug
