### ISSUE TITLE
Should this be used with cloudformation templates?

### ISSUE THREAD

**Issue by exiadbq** [DataDog/datadog-cloudformation-macro#25] opened 2021-01-15 04:11 UTC
https://github.com/DataDog/datadog-cloudformation-macro#datadog-cloudformation-macro
read me says yes,

sub folder no mentioning
https://github.com/DataDog/datadog-cloudformation-macro/tree/master/serverless#datadog-serverless-macro

Support guy suggest it should work with CF templates, but seems not clear, or not sure if working.

**Comment by tianchu** [comment] 2021-01-15 15:01
This macro primarily focuses on AWS SAM and CDK use cases, but it should work for CloudFormation projects too. Let us know if you encounter any issue. For quick questions like this, you could also find us in our [slack community](https://github.com/DataDog/datadog-cloudformation-macro/tree/master/serverless#community).

**Comment by exiadbq** [comment] 2021-01-21 13:45
```
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      nodeLayerVersion: 43
      forwarderArn:
        Fn::ImportValue: datadog-forwarder-ForwarderArn
```
I got the same error while generating changeset for my cfn template on template level, I didn't add `service` param as my template has multiple fn and each can be it's own service.

`The value of parameter forwarderArn under transform DatadogServerless must resolve to a string, number, boolean or a list of any of these.`
Which may or may not relate to https://github.com/aws/serverless-application-model/issues/22?

**Comment by tianchu** [comment] 2021-01-21 14:20
@exiadbq you are right, your issue and https://github.com/aws/serverless-application-model/issues/22 are due to the same root cause -- CFN passes the **raw** template to the macro for transformation, i.e., our macro sees `Fn::ImportValue: datadog-forwarder-ForwarderArn` instead of the actual value of the forwarder ARN, so it's not gonna work. 

The workaround is to NOT define the `forwarderArn` parameter (which creates the subscription filters behind scene) and instead you define subscription filters on your functions' log groups in your SAM/CFN template. Similar to what is described [here](https://github.com/DataDog/datadog-cloudformation-macro/tree/master/serverless#error-message-functionname-property-is-undefined-for).

I'm going to close this issue, since I think this kind of questions are better suited for our [slack community](https://chat.datadoghq.com/).

**Closed by tianchu** 2021-01-21 14:20 UTC
